Out-of-the-box, Micronaut supports https://tools.ietf.org/html/rfc7617[RFC7617] which defines the "Basic" Hypertext Transfer Protocol (HTTP) authentication scheme, which transmits credentials as user-id/password pairs, encoded using Base64. Basic authentication is enabled by default.

The following sequence illustrates the authentication flow:

image::basicauth.svg[]

Below is a sample of a cURL command using basic auth:

[source, bash]
.cURL command using Basic Auth
----
curl "http://localhost:8080/info" \
     -u 'user:password'
----

After credentials are read from the HTTP Header, they are feed into an link:{api}/io/micronaut/security/authentication/Authenticator.html[Authenticator]
which attempts to validate them.

The code snippet below illustrates how to send credentials using the `basicAuth` method from api:http.MutableHttpRequest[] method:

[source, groovy]
.Accessing a protected resource using an Authorization request header
----
include::{testssecurity}/security/token/basicauth/BasicAuthSpec.groovy[tag=basicAuth, indent=0]
----

The following configuration properties are available to customize basic authentication behaviour:

include::{includedir}configurationProperties/io.micronaut.security.token.basicauth.BasicAuthTokenReaderConfigurationProperties.adoc[]

TIP: Read the http://guides.micronaut.io/micronaut-security-basicauth/guide/index.html[Basic Authentication Micronaut Guide] to learn more.
