Micronaut supports Session based authentication.

[TIP]
.Using the CLI
====
If you are creating your project using the Micronaut CLI, supply either the `security-session` feature to configure session security in your project:
----
$ mn create-app my-app --features security-session
----
====


To use the Micronaut's session based authentication capabilities you must have the `security-session` dependency on your classpath. For example:

dependency:io.micronaut.security:micronaut-security-annotations[scope='annotationProcessor']

dependency:io.micronaut.security:micronaut-security-session[]

NOTE: The `micronaut-security-annotations` dependency is only required to use JSR 250 annotations

The following sequence illustrates the authentication flow:

image::sesssion_based_auth.svg[]

Check the <<redirection, Redirection configuration>> to customize session based authentication behaviour.

== Example of Session-Based Authentication configuration

[source, yaml]
----
include::{testssecuritysession}/security/session/SessionAuthenticationSpec.groovy[tag=yamlconfig,indent=0]
----

TIP: Read the https://guides.micronaut.io/micronaut-security-session/guide/index.html[Session-Based Authentication Micronaut Guide] to learn more.
