package io.micronaut.security.password.argon2.bouncycastle;

import io.micronaut.context.ApplicationContext;
import io.micronaut.context.exceptions.BeanInstantiationException;
import io.micronaut.security.password.PasswordEncoder;
import io.micronaut.security.password.argon2.Argon2HashFunction;
import io.micronaut.security.password.argon2.Argon2PasswordEncoderConfigurationProperties;
import io.micronaut.security.password.argon2.Argon2PhcString;
import jakarta.validation.ConstraintViolationException;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;
import org.junit.jupiter.params.provider.NullSource;
import org.junit.jupiter.params.provider.ValueSource;

import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class Argon2PasswordEncoderTest {
    private static final String PASSWORD = "correct horse battery staple";
    private static final String SALT_AND_HASH = "$" + "A".repeat(22) + "$" + "A".repeat(43);

    @Test
    void encodesWithTheDefaultParameters() {
        PasswordEncoder encoder = encoder(new Argon2PasswordEncoderConfigurationProperties());
        String encoded = encoder.encode(PASSWORD);

        assertTrue(encoded.startsWith("$argon2id$v=19$m=19456,t=2,p=1$"));
        Argon2PhcString phc = Argon2PhcString.parse(encoded);
        assertNotNull(phc);
        assertEquals(16, phc.salt().length);
        assertEquals(32, phc.hash().length);
        assertTrue(encoder.matches(PASSWORD, encoded));
    }

    @Test
    void configurationBindsToTheEncoderBean() {
        try (ApplicationContext context = ApplicationContext.run(Map.of(
            "micronaut.security.password.argon2.memory", 256,
            "micronaut.security.password.argon2.iterations", 3,
            "micronaut.security.password.argon2.parallelism", 2,
            "micronaut.security.password.argon2.salt-length", 8,
            "micronaut.security.password.argon2.hash-length", 12
        ))) {
            PasswordEncoder encoder = context.getBean(PasswordEncoder.class);
            Argon2HashFunction hashFunction = context.getBean(Argon2HashFunction.class);
            assertInstanceOf(BouncyCastleArgon2HashFunction.class, hashFunction);
            assertEquals(BouncyCastleArgon2HashFunction.NAME, hashFunction.getName());
            String encoded = encoder.encode(PASSWORD);
            assertTrue(encoded.startsWith("$argon2id$v=19$m=256,t=3,p=2$"));
            Argon2PhcString phc = Argon2PhcString.parse(encoded);
            assertNotNull(phc);
            assertEquals(8, phc.salt().length);
            assertEquals(12, phc.hash().length);
            assertTrue(encoder.matches(PASSWORD, encoded));
        }
    }

    @ParameterizedTest
    @CsvSource({
        // Argon2 reference vectors and hashes generated by Spring Security using Bouncy Castle.
        "password, '$argon2id$v=19$m=65536,t=2,p=1$c29tZXNhbHQ$CTFhFdXPJO1aFaMaO6Mm5c8y7cJHAph8ArZWb2GRPPc'",
        "password, '$argon2id$v=19$m=256,t=2,p=2$c29tZXNhbHQ$bQk8UB/VmZZF4Oo79iDXuL5/0ttZwg2f/5U52iv1cDc'",
        "correct horse battery staple, '$argon2id$v=19$m=16384,t=2,p=1$oD4J6tHQEKFFoGSw8uyJyg$PaHHvg2gl1OKYaPxIveAoFJ2jqi5s8ovKOtXSaLte+0'",
        "pässwörd-密码-🔐, '$argon2id$v=19$m=16384,t=2,p=1$9Qn2FOuD/EI7hi34pX2m2w$uSEl4qIaL4M+Jbs7Gvrt7YxY+rVOat+MwRlrU0yE9k4'",
    })
    void matchesHashesFromOtherImplementations(String password, String encoded) {
        PasswordEncoder encoder = encoder(new Argon2PasswordEncoderConfigurationProperties());

        assertTrue(encoder.matches(password, encoded));
        assertFalse(encoder.matches(password + "!", encoded));
    }

    @Test
    void verifiesHashesWithDifferentParameters() {
        Argon2PasswordEncoderConfigurationProperties configured = configuration(512, 3, 2);
        String encoded = encoder(configured).encode(PASSWORD);

        assertTrue(encoder(configuration(256, 1, 1)).matches(PASSWORD, encoded));
    }

    @ParameterizedTest
    @NullSource
    @ValueSource(strings = {"", " ", "\t", "\n"})
    void rejectsBlankPasswords(String blank) {
        PasswordEncoder encoder = encoder(configuration(256, 1, 1));
        String encoded = encoder.encode(PASSWORD);

        assertThrows(ConstraintViolationException.class, () -> encoder.encode(blank));
        assertThrows(ConstraintViolationException.class, () -> encoder.matches(blank, encoded));
        assertThrows(ConstraintViolationException.class, () -> encoder.matches(PASSWORD, blank));
    }

    @ParameterizedTest
    @ValueSource(strings = {
        "not-an-encoded-password",
        "$argon2i$v=19$m=256,t=1,p=1$AAAAAAAAAAAAAAAAAAAAAA$AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "$argon2id$v=16$m=256,t=1,p=1$AAAAAAAAAAAAAAAAAAAAAA$AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "$argon2id$v=19$m=256,t=1,p=1$AAAAAAAAAAAAAAAAAAAAA=$AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    })
    void rejectsMalformedHashes(String encoded) {
        assertFalse(encoder(configuration(256, 1, 1)).matches(PASSWORD, encoded));
    }

    @ParameterizedTest
    @ValueSource(strings = {
        "m=1025,t=1,p=1",
        "m=256,t=5,p=1",
        "m=7,t=1,p=1",
        "m=15,t=1,p=2",
    })
    void rejectsUnsafeHashParameters(String parameters) {
        Argon2PasswordEncoderConfigurationProperties configuration = configuration(256, 1, 1);
        configuration.setMaxMemory(1024);
        configuration.setMaxIterations(4);

        assertFalse(encoder(configuration).matches(PASSWORD, "$argon2id$v=19$" + parameters + SALT_AND_HASH));
    }

    @Test
    void rejectsInvalidConfiguration() {
        Argon2PasswordEncoderConfigurationProperties configuration = configuration(15, 1, 2);

        BeanInstantiationException exception = assertThrows(BeanInstantiationException.class, () -> encoder(configuration));
        assertTrue(exception.getMessage().contains("memory - must be between 16 and 262144"));
    }

    private static Argon2PasswordEncoderConfigurationProperties configuration(int memory, int iterations, int parallelism) {
        Argon2PasswordEncoderConfigurationProperties configuration = new Argon2PasswordEncoderConfigurationProperties();
        configuration.setMemory(memory);
        configuration.setIterations(iterations);
        configuration.setParallelism(parallelism);
        return configuration;
    }

    private static PasswordEncoder encoder(Argon2PasswordEncoderConfigurationProperties configuration) {
        String prefix = Argon2PasswordEncoderConfigurationProperties.PREFIX;
        try (ApplicationContext context = ApplicationContext.run(Map.of(
            prefix + ".memory", configuration.getMemory(),
            prefix + ".iterations", configuration.getIterations(),
            prefix + ".parallelism", configuration.getParallelism(),
            prefix + ".salt-length", configuration.getSaltLength(),
            prefix + ".hash-length", configuration.getHashLength(),
            prefix + ".max-memory", configuration.getMaxMemory(),
            prefix + ".max-iterations", configuration.getMaxIterations()
        ))) {
            return context.getBean(PasswordEncoder.class);
        }
    }
}
