package io.micronaut.security.password.argon2.bouncycastle;

import io.micronaut.context.ApplicationContext;
import io.micronaut.security.password.PasswordEncoder;
import io.micronaut.security.password.argon2.Argon2HashFunction;
import io.micronaut.security.password.argon2.Argon2PasswordEncoderConfigurationProperties;
import io.micronaut.security.password.argon2.Argon2PhcString;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class Argon2PasswordEncoderTest {
    private static final String PASSWORD = "correct horse battery staple";

    @Test
    void encodesWithTheDefaultParameters() {
        PasswordEncoder encoder = encoder(new Argon2PasswordEncoderConfigurationProperties());
        String encoded = encoder.encode(PASSWORD);

        assertTrue(encoded.startsWith("$argon2id$v=19$m=19456,t=2,p=1$"));
        Argon2PhcString phc = Argon2PhcString.parse(encoded);
        assertNotNull(phc);
        assertEquals(16, phc.salt().length);
        assertEquals(32, phc.hash().length);
        assertTrue(encoder.matches(PASSWORD, encoded));
    }

    @Test
    void configurationBindsToTheEncoderBean() {
        try (ApplicationContext context = ApplicationContext.run(Map.of(
            "micronaut.security.password.argon2.memory", 256,
            "micronaut.security.password.argon2.iterations", 3,
            "micronaut.security.password.argon2.parallelism", 2,
            "micronaut.security.password.argon2.salt-length", 8,
            "micronaut.security.password.argon2.hash-length", 12
        ))) {
            PasswordEncoder encoder = context.getBean(PasswordEncoder.class);
            Argon2HashFunction hashFunction = context.getBean(Argon2HashFunction.class);
            assertInstanceOf(BouncyCastleArgon2HashFunction.class, hashFunction);
            assertEquals(BouncyCastleArgon2HashFunction.NAME, hashFunction.getName());
            String encoded = encoder.encode(PASSWORD);
            assertTrue(encoded.startsWith("$argon2id$v=19$m=256,t=3,p=2$"));
            Argon2PhcString phc = Argon2PhcString.parse(encoded);
            assertNotNull(phc);
            assertEquals(8, phc.salt().length);
            assertEquals(12, phc.hash().length);
            assertTrue(encoder.matches(PASSWORD, encoded));
        }
    }

    @ParameterizedTest
    @CsvSource({
        // Argon2 reference vectors and hashes generated by Spring Security using Bouncy Castle.
        "password, '$argon2id$v=19$m=65536,t=2,p=1$c29tZXNhbHQ$CTFhFdXPJO1aFaMaO6Mm5c8y7cJHAph8ArZWb2GRPPc'",
        "password, '$argon2id$v=19$m=256,t=2,p=2$c29tZXNhbHQ$bQk8UB/VmZZF4Oo79iDXuL5/0ttZwg2f/5U52iv1cDc'",
        "correct horse battery staple, '$argon2id$v=19$m=16384,t=2,p=1$oD4J6tHQEKFFoGSw8uyJyg$PaHHvg2gl1OKYaPxIveAoFJ2jqi5s8ovKOtXSaLte+0'",
        "pässwörd-密码-🔐, '$argon2id$v=19$m=16384,t=2,p=1$9Qn2FOuD/EI7hi34pX2m2w$uSEl4qIaL4M+Jbs7Gvrt7YxY+rVOat+MwRlrU0yE9k4'",
    })
    void matchesHashesFromOtherImplementations(String password, String encoded) {
        PasswordEncoder encoder = encoder(new Argon2PasswordEncoderConfigurationProperties());

        assertTrue(encoder.matches(password, encoded));
        assertFalse(encoder.matches(password + "!", encoded));
    }

    @Test
    void verifiesHashesWithDifferentParameters() {
        Argon2PasswordEncoderConfigurationProperties configured = configuration(512, 3, 2);
        String encoded = encoder(configured).encode(PASSWORD);

        assertTrue(encoder(configuration(256, 1, 1)).matches(PASSWORD, encoded));
    }

    @Test
    void anUnpairedSurrogateIsNotReplacedBeforeHashing() {
        BouncyCastleArgon2HashFunction hashFunction = new BouncyCastleArgon2HashFunction();
        byte[] salt = new byte[16];

        assertThrows(IllegalStateException.class, () -> hashFunction.hash("\uD800", salt, 256, 1, 1, 32));
    }

    @Test
    void aPasswordWithAnUnpairedSurrogateDoesNotMatchItsReplacement() {
        PasswordEncoder encoder = encoder(configuration(256, 1, 1));
        String encoded = encoder.encode("?");

        assertTrue(encoder.matches("?", encoded));
        assertFalse(encoder.matches("\uD800", encoded));
    }

    private static Argon2PasswordEncoderConfigurationProperties configuration(int memory, int iterations, int parallelism) {
        Argon2PasswordEncoderConfigurationProperties configuration = new Argon2PasswordEncoderConfigurationProperties();
        configuration.setMemory(memory);
        configuration.setIterations(iterations);
        configuration.setParallelism(parallelism);
        return configuration;
    }

    private static PasswordEncoder encoder(Argon2PasswordEncoderConfigurationProperties configuration) {
        String prefix = Argon2PasswordEncoderConfigurationProperties.PREFIX;
        try (ApplicationContext context = ApplicationContext.run(Map.of(
            prefix + ".memory", configuration.getMemory(),
            prefix + ".iterations", configuration.getIterations(),
            prefix + ".parallelism", configuration.getParallelism(),
            prefix + ".salt-length", configuration.getSaltLength(),
            prefix + ".hash-length", configuration.getHashLength(),
            prefix + ".max-memory", configuration.getMaxMemory(),
            prefix + ".max-iterations", configuration.getMaxIterations()
        ))) {
            return context.getBean(PasswordEncoder.class);
        }
    }
}
