This section will document breaking changes that may happen during milestone or release candidate releases, as well as major releases eg (1.x.x -> 2.x.x).

=== User Details Removal

The `UserDetails` class has been removed and all usages should be replaced with api:security.authentication.Authentication[].

==== Affected APIs

- api:security.authentication.AuthenticationFailed[]
- api:security.authentication.AuthenticationResponse[]
- api:security.handlers.LoginHandler[]
- api:security.rules.AbstractSecurityRule[]
- api:security.rules.SecurityRule[]
- api:security.rules.SensitiveEndpointRule[]
- api:security.token.event.RefreshTokenGeneratedEvent[]
- api:security.token.generator.RefreshTokenGenerator[]
- api:security.token.generator.TokenGenerator[]
- api:security.token.jwt.cookie.CookieLoginHandler[]
- api:security.token.jwt.generator.AccessRefreshTokenGenerator[]
- api:security.token.jwt.generator.claims.ClaimsGenerator[]
- api:security.token.jwt.render.TokenRenderer[]
- api:security.token.refresh.RefreshTokenPersistence[]

==== Classes Renamed

|===
|Old |New

| io.micronaut.security.oauth2.endpoint.token.response.OauthUserDetailsMapper
| io.micronaut.security.oauth2.endpoint.token.response.OauthAuthenticationMapper

| io.micronaut.security.oauth2.endpoint.token.response.OpenIdUserDetailsMapper
| io.micronaut.security.oauth2.endpoint.token.response.OpenIdAuthenticationMapper

| io.micronaut.security.oauth2.endpoint.token.response.DefaultOpenIdUserDetailsMapper
| io.micronaut.security.oauth2.endpoint.token.response.DefaultOpenIdAuthenticationMapper

|===

==== Other Changes

- The api:security.event.LoginSuccessfulEvent[] that gets emitted when a user logs in will now be created with an instance of api:security.authentication.Authentication[].
- The `AuthenticationUserDetailsAdapter` class has been deleted.

=== SecurityRule Changes

The api:security.rules.SecurityRule[] API has changed. The last argument to the method was a map that represented the user attributes. Instead that argument was replaced with a reference to the api:security.authentication.Authentication[]. This has the benefit of rules now having access to the username of the logged in user as well as access to the convenience method `getRoles()`.

In addition, the return type of the method has changed to return a `Publisher`. This was necessary because the security rules execute as part of the security filter which may be on a non blocking thread. Because the method now returns a `Publisher`, blocking operations can be offloaded to another thread pool using the reactive streams implementation of your choice.

Micronaut 2 API:

`SecurityRuleResult check(HttpRequest<?> request, @Nullable RouteMatch<?> routeMatch, @Nullable Map<String, Object> claims);`

Micronaut 3 API:

`Publisher<SecurityRuleResult> check(HttpRequest<?> request, @Nullable RouteMatch<?> routeMatch, @Nullable Authentication authentication);`

=== LDAP Package Change

All classes in the `io.micronaut.configuration.security.ldap` have been moved to the `io.micronaut.security.ldap` package.

=== SecurityFilter

The security filter no longer extends deprecated `OncePerRequestHttpServerFilter` because it has been deprecated in Micronaut 3.

=== Cookie Secure Configuration

The following properties' default value has been removed in Micronaut Security 3.0.0:

- `micronaut.security.oauth2.openid.nonce.cookie.cookie-secure`
- `micronaut.security.oauth2.state.cookie.cookie-secure`
- `micronaut.security.token.jwt.cookie.cookie-secure`
- `micronaut.security.token.refresh.cookie.cookie-secure``

NOTE: If the `cookie-secure` setting is not set, cookies will be secure if the request is determined to be HTTPS.

=== Deprecations Removal

Most if not all deprecated classes constructors, and methods have been removed.

=== Other Changes

- The constructor of api:security.token.jwt.validator.DefaultJwtAuthenticationFactory[] has changed
- The constructor of api:security.oauth2.endpoint.token.response.IdTokenLoginHandler[] has changed
- The constructor of api:security.session.SessionLoginHandler[] has changed
- The constructor of api:security.authentication.BasicAuthAuthenticationFetcher[] has changed
- The api:io.micronaut.security.token.RolesFinder[] method `findInClaims` has been deprecated and usages should be replaced with `resolveRoles(@Nullable Map<String, Object> attributes)`.
