This section will document breaking changes that may happen during milestone or release candidate releases, as well as major releases eg (1.x.x -> 2.x.x).

== 3.0.0

=== What's New

==== SecurityRule API Change

- `SecurityRule::check` method receives an `Authentication` instance instead of a claims Map. The method signature was:

`SecurityRuleResult check(HttpRequest<?> request, @Nullable RouteMatch<?> routeMatch, @Nullable  Map<String, Object> claims);`

In Micronaut Security 3.0 is:

`SecurityRuleResult check(HttpRequest<?> request, @Nullable RouteMatch<?> routeMatch, @Nullable Authentication authentication);`

==== User Details removal

- `UserDetails` has been removed. `Authentication` should be used instead. Moreover, several static methods to `AuthenticationResponse` and `Authentication` to ease the instances of those interfaces.
API replaces the use of `UserDetails` with `Authentication`.
- `RefreshTokenPersistence` extends `ApplicationEventListener<RefreshTokenGeneratedEvent>`.

==== Cookie secure default value

- Package `io.micronaut.configuration.security.ldap` has been renamed to `io.micronaut.security.ldap`

- `SecurityFilter` no longer extends deprecated `OncePerRequestHttpServerFilter`. Instead, it implements `HttpServerFilter`.


The following properties' default value has been removed in Micronaut Security 3.0.0:

- `micronaut.security.oauth2.openid.nonce.cookie.cookie-secure`
- `micronaut.security.oauth2.state.cookie.cookie-secure`
- `micronaut.security.token.jwt.cookie.cookie-secure`
- `micronaut.security.token.refresh.cookie.cookie-secure``

NOTE: If the `cookie-secure` setting is not set, cookies will be secure if the request is determined to be HTTPS.

=== 3.0.0 Deprecations removal

Micronaut security:

- Deletes deprecated methods `JwtValidator::validate(String)` and `JwtValidator::validate(JWT)`
- Deletes deprecated class `SecuritySessionConfiguration`
- Deletes deprecated constructor `JwtCookieClearerLogoutHandler(JwtCookieConfiguration)`
- Deletes deprecated constructor `CookieLoginHandler(JwtCookieConfiguration, RedirectConfiguration redirectConfiguration, PriorToLoginPersistence priorToLoginPersistence)`
- Deletes deprecated constructor `CookieLoginHandler(JwtCookieConfiguration,String, String)`
- Deletes deprecated constructor `DefaultOpenIdAuthenticationMapper`
- Deletes deprecated constructors `JwtCookieLoginHandler(JwtCookieConfiguration, AccessTokenConfiguration, AccessRefreshTokenGenerator accessRefreshTokenGenerator)`, `JwtCookieLoginHandler(RedirectConfiguration,JwtCookieConfiguration,AccessTokenConfiguration,AccessRefreshTokenGenerator accessRefreshTokenGenerator,PriorToLoginPersistence priorToLoginPersistence)`
- Deletes deprecated constructor `IdTokenLoginHandler(JwtCookieConfiguration,RedirectConfiguration,TokenConfiguration,PriorToLoginPersistence)`
- Deletes deprecated constructor `JwtCookieTokenReader(JwtCookieConfiguration)`
- Deletes deprecated method `DefaultOauthClient::getTokenEndpoint`
- Deletes `DefaultSecurityService#ROLES`
- Deletes deprecated method `OauthUserDetailsMapper::createUserDetails(TokenResponse)`
- Deletes `TokenValidator::validateToken(String)`
- Deletes deprecated constructor `SessionLoginHandler(SecuritySessionConfiguration,SessionStore<Session>,TokenConfiguration)`
- Deletes deprecated constructor `TokenRefreshRequest(String)`
- Deletes deprecated method `SecurityService::hasRole`
- Deletes deprecated class `TokenResponseExpiration`
- Deletes deprecated constructor `DefaultSecurityService(TokenConfiguration)`.
- Deletes deprecated method `OpenIdAuthenticationMapper:createAuthenticationResponse(String, OpenIdTokenResponse, OpenIdClaims)`
- Deletes deprecated method `BasicAuthAuthenticationFetcher::parseCredentials`
- Deletes deprecated classes `JwtGeneratorConfiguration` and JwtGeneratorConfigurationProperties`
- Deletes deprecated method `JwtClaimsValidator:validate(JwtClaims)`
- Deletes deprecated constructor `JWTClaimsSetGenerator(TokenConfiguration,JwtIdGenerator, ClaimsAudienceProvider)`
- Deletes deprecated constructor `RefreshTokenGeneratedEvent(Object)`

== 2.0.0

=== New Maven Group ID

The Maven Group ID has changed from `io.micronaut` to `io.micronaut.security`.

=== Modules Enabled by default

* Modules are now enabled by default. The configuration keys `micronaut.security.enabled`, `micronaut.security.token.jwt.enabled`, `micronaut.security.oauth2.enabled`, and `micronaut.security.session.enabled` are now all `true` by default.

=== Endpoints enabled by default

* You don't need to enable Endpoints. The configuration keys `micronaut.security.endpoints.keys.enabled`, `micronaut.security.endpoints.login.enabled`, `micronaut.security.endpoints.logout.enabled`, `micronaut.security.endpoints.oauth.enabled` are now all `true` by default. However, You will need to provide the required beans for each endpoint.

=== Authentication Provider

* The api:security.authentication.AuthenticationProvider[] API has changed to include the HTTP request as a parameter. Thus, it is now possible to gain access to the request in your api:security.authentication.AuthenticationProvider[]. Simply override the default method in the interface that takes the request as an argument with your own implementation. The old method is no longer called from the framework.

* It is no longer assumed that a failed authentication response is an instance of api:security.authentication.AuthenticationFailed[]. That now allows for any subclass of api:security.authentication.AuthenticationResponse[] to be emitted in the case of an authentication failure.

* Previously api:security.authentication.AuthenticationProvider[]s were allowed to return hot observables, meaning the logic to authenticate the user could be done upon execution of the method. Allowing for that behavior caused the logic to execute the authenticators to be difficult to maintain. Now providers must return cold observables. The `authenticate` method will be executed for every authentication provider for every authentication request. If you were previously doing the authentication work then using something like `Flowable.just`, you must use something like `Flowable.create` to create a cold observable.

=== Delegating Authentication Provider

* The `DelegatingAuthenticationProvider` and it's related interfaces has been removed. If you provided implementations for `UserFetcher`, `UserState`, `PasswordEncoder`, and `AuthoritiesFetcher`, integrate them into your own implementation of api:security.authentication.AuthenticationProvider[]. This API was removed because it only served a niche use case and increased the surface of this library's API. None of the classes mentioned were directly used in this library and thus belong in the realm of user's applications. Check https://guides.micronaut.io/latest/micronaut-database-authentication-provider.html[LDAP and Database authentication providers tutorial] to learn how to write a `DelegatingAuthenticationProvider`.

=== LdapAuthenticationProvider

The constructor for api:configuration.security.ldap.LdapAuthenticationProvider[] has been changed to accept an executor to schedule the LDAP lookup operation on. By default it is now scheduled on the IO thread pool.

=== LoginHandler

* The api:security.handlers.LoginHandler[] API has changed to accept an api:security.authentication.AuthenticationResponse[] object instead of an api:security.authentication.AuthenticationFailed[].

* Previously, `AccessRefreshTokenLoginHandler` was enabled by default. Currently, no `LoginHandler` is enabled by default. If you wish to use any of the built-in `LoginHandler`s, you have to set the configuration:

** `micronaut.security.authentication: bearer` to enable api:security.token.jwt.bearer.AccessRefreshTokenLoginHandler[]
** `micronaut.security.authentication: cookie` to enable api:security.token.jwt.cookie.JwtCookieLoginHandler[]
** `micronaut.security.authentication: session` to enable api:security.session.SessionLoginHandler[]
** `micronaut.security.authentication: idtoken` to enable api:security.oauth2.endpoint.token.response.IdTokenLoginHandler[]

==== Migration Example A

If you were using the default bearer authentication, you should set:

```yaml
micronaut:
    security:
        authentication: bearer
```

==== Migration Example B

For a previous configuration such as:

```yaml
micronaut:
    security:
        token:
            jwt:
                bearer:
                     enabled: false
                cookie:
                     enabled: true
```

use instead:

```yaml
micronaut:
    security:
        authentication: cookie
```

=== LogoutHandler

* To use any of the built-in api:security.handlers.LogoutHandler[] you have to set the configuration:

** `micronaut.security.authentication:` `cookie` or `idtoken` to enable api:security.token.jwt.cookie.JwtCookieClearerLogoutHandler[]
** `micronaut.security.authentication: session` to enable api:security.session.SessionLogoutHandler[]

=== Refresh Token

* The story around refresh tokens has been changed. There were a couple of core issues with the old implementation that needed resolved.
+
** The refresh tokens were JWT tokens which also allowed them to be used to access resources.
** Because they never expire (by default), it requires a list of invalid tokens to be maintained in perpetuity if the ability to revoke tokens is a requirement. `JwtGeneratorConfiguration#getRefreshTokenExpiration` is deprecated and it is no longer used.
** The refresh mechanism simply copied the claims from the refresh token JWT back into a new access token. This made any changes to the state of the user (new roles, etc) were not be applied at the time of refresh.
+
The functionality has now been changed to generate a token that is not a JWT, but is instead a signed token of a unique key. The default implementation signs a UUID with a secret provided via configuration. After the token is generated, it is up to each application to provide an implementation of api:security.token.refresh.RefreshTokenPersistence[] to store the token and link it to the user it was created for. That is essential to generate new claims information in new access tokens created by the refresh endpoint. See the <<refresh, refresh section>> for more information.

=== Rejection Handler

* The legacy rejection handler in the session module, which was enabled by default, has been removed. The setting `micronaut.security.session.legacy-rejection-handler` no longer has any effect and is equivalent to the behavior of `false` in previous versions.

* The entire `RejectionHandler` API and its dependents have been removed in favor of using the built in exception handling API in Micronaut. An api:security.authentication.AuthorizationException[] will now be emitted when access to a resource has been rejected. A default exception handler has been created that will redirect on forbidden or unauthorized if the accept header of the request allows for text/html. For bearer authentication, that behavior can be disabled with:
+
```yaml
micronaut.security.redirect.forbidden.enabled: false
micronaut.security.redirect.unauthorized.enabled: false
```
+


=== Basic Auth

* Basic authentication configuration has moved from `micronaut.security.token.basic-auth` to `micronaut.security.basic-auth`. The implementation surrounding basic authentication has changed and some classes have been deleted. If you have not overridden any beans related to basic authentication, the functionality will remain the same as it was. Previously a `TokenValidatedEvent` was triggered as a result of basic authentication, however that is no longer the case.

=== TokenPropagation

Several classes related to <<tokenPropagation, token propagation>> have been renamed and relocated:

|===
| Old | New

| `io.micronaut.security.token.writer.HttpHeaderTokenWriter`
| api:io.micronaut.security.token.propagation.HttpHeaderTokenPropagator[]

| `io.micronaut.security.token.writer.HttpHeaderTokenWriterConfiguration`
| api:io.micronaut.security.token.propagation.HttpHeaderTokenPropagatorConfiguration[]

| `io.micronaut.security.token.writer.HttpHeaderTokenWriterConfigurationProperties`
| api:io.micronaut.security.token.propagation.HttpHeaderTokenPropagatorConfigurationProperties[]

| `io.micronaut.security.token.writer.TokenWriter`
| api:io.micronaut.security.token.propagation.TokenPropagator[]

|===

Read <<tokenPropagation, token propagation>> section to learn more.

=== Misc

* Several APIs that lacked generics have been changed to add them. For example `HttpRequest` -> `HttpRequest<?>`.

* Several APIs have been changed to return api:http.MutableHttpResponse[] instead of api:http.HttpResponse[].

* The SecurityFilterOrderProvider API has been deleted in favor of the standard ServerFilterPhase class. The security filter will now run on the order defined by the SECURITY phase.

* The io.micronaut.security.token.jwt.signature.secret.SecretSignatureFactory was deleted because the beans can be created directly from the SecretSignature class.

* api:security.token.jwt.generator.AccessRefreshTokenGenerator[] is now the interface which defines how generate a api:security.token.jwt.render.AccessRefreshToken[] for a particular user. The implementation has been moved to api:security.token.jwt.generator.DefaultAccessRefreshTokenGenerator[].

=== Deprecated

* All deprecations present in 1.3.x have been removed.

* `JwtGeneratorConfiguration` has been deprecated in favor of api:security.token.jwt.generator.AccessTokenConfiguration[]. The configuration has been changed from `micronaut.security.token.jwt.generator.access-token-expiration` to `micronaut.security.token.jwt.generator.access-token.expiration`.

==== Redirection

* Redirection configuration has been simplified. The properties in the first column are deprecated and will be removed in a future version. The properties on the right should be used instead. All properties are prefixed with `micronaut.security`.

[options="header"]
|=========================================================
|Old |New
|`micronaut.security.session.login-success-target-url` |`micronaut.security.redirect.login-success`
|`micronaut.security.session.login-failure-target-url` |`micronaut.security.redirect.login-failure`
|`micronaut.security.session.logout-target-url` |`micronaut.security.redirect.logout`
|`micronaut.security.session.unauthorized-target-url` |`micronaut.security.redirect.unauthorized.url`
|`micronaut.security.session.forbidden-target-url` |`micronaut.security.redirect.forbidden.url`
|`micronaut.security.session.redirect-on-rejection` |`micronaut.security.redirect.unauthorized.enabled` and `micronaut.security.redirect.forbidden.enabled`
|`micronaut.security.token.jwt.cookie.logout-target-url` | `micronaut.security.redirect.logout`
|`micronaut.security.token.jwt.cookie.login-success-target-url` |`micronaut.security.redirect.login-success`
|`micronaut.security.token.jwt.cookie.login-failure-target-url` |`micronaut.security.redirect.login-failure`
|=========================================================
