Imagine you have a Gateway microservice which consumes three other microservices:

image::tokenpropagation.svg[]

If the incoming request `localhost:8080/api/books` contains a valid JWT token, you may want to propagate
that token to other requests in your network.

You can configure token propagation to achieve that.

[source, yaml]
----
include::{testssecurity}/security/token/propagation/TokenPropagationSpec.groovy[tag=yamlconfig,indent=0]
----

The previous configuration, configures a link:{api}/io/micronaut/security/token/propagation/HttpHeaderTokenPropagator.html[HttpHeaderTokenPropagator] and a
and a propagation filter, link:{api}/io/micronaut/security/token/propagation/TokenPropagationHttpClientFilter.html[TokenPropagationHttpClientFilter], which
will propagate the security token seamlessly.

If you use <<serviceDiscovery, Service Discovery>> features, you can use the service id in your service id regular expression:

[source, bash]
----
micronaut.security.token.propagation.service-id-regex="catalogue|recommendations|inventory"
----

Several configuration options are available:

include::{includedir}configurationProperties/io.micronaut.security.token.propagation.TokenPropagationConfigurationProperties.adoc[]

For propagation via an HTTP Header, you can configure:

include::{includedir}configurationProperties/io.micronaut.security.token.propagation.HttpHeaderTokenPropagatorConfigurationProperties.adoc[]

TIP: Read the https://guides.micronaut.io/micronaut-token-propagation/guide/index.html[Token Propagation tutorial] to learn more.

