Micronaut Security {version} includes changes to make the transition to version 2.0 easier.

== Deprecations

* Most of the methods in api:security.token.jwt.validator.JwtTokenValidator[] and the api:security.token.jwt.validator.JwtTokenValidatorUtils[] class has been deprecated in favor of a new builder style syntax. The new class is api:security.token.jwt.validator.JwtValidator[]. Replace any deprecated usage with the builder style validator.

* The entire api:security.handlers.RejectionHandler[] API has been deprecated in favor of usage of the existing exception handler functionality in Micronaut. A new exception, api:security.authentication.AuthorizationException[], has been created and will be emitted from the security filter. To bridge that API with the current one, a api:security.authentication.DefaultAuthorizationExceptionHandler[] has been created that delegates to the current api:security.handler.RejectionHandler[] API. If you have your own rejection handler, it is recommended to replace the default exception handler with your own implementation.

* The api:security.handlers.LoginHandler#loginFailed-io.micronaut.security.authentication.AuthenticationFailed-[LoginHandler#loginFailed] method has been deprecated. Override the new default method that takes an api:security.authentication.AuthenticationResponse[] instead.

* The api:security.authentication.providers.DelegatingAuthenticationProvider[] and its related APIs have been deprecated and will be removed in a future release without any replacement. If your application currently overrides these APIs, copy the code into your codebase.

* The api:security.token.writer.TokenWriter[] api has been deprecated in favor of api:security.token.propagation.TokenPropagator[].

== Annotation Processing

* The ann:security.annotation.Secured[] annotation has been moved to a separate module in order to reduce the number of classes in the annotation processor scope. If you currently have `micronaut-security` in the classpath of your compiler, the entry can be changed to `micronaut-security-annotations`.

== Improvements

* It is now possible to gain access to the request in your api:security.authentication.AuthenticationProvider[]. Simply override the default method in the interface that takes the request as an argument with your own implementation. The old method is no longer called from the framework.

* It is no longer assumed that a failed authentication response is an instance of api:security.authentication.AuthenticationFailed[]. That now allows for any subclass of api:security.authentication.AuthenticationResponse[] to be emitted in the case of an authentication failure.

* A new constructor for api:security.authentication.AuthenticationFailed[] that takes a string message has been added to allow for custom error messages.

* It is now possible to require all api:security.authentication.AuthenticationProvider[]s to return a successful authentication response. Set `micronaut.security.authentication-strategy: ALL` to enable this functionality.

* The token propagation implementation will now no longer override an existing token.

* It is now possible to allow for requests that would normally result in a 404 to return with 404 instead of almost always returning a 401 or 403. The current behavior is still the default because it prevents attackers from discovering what endpoints are available in your application. To enable the alternative behavior, set `micronaut.security.reject-not-found: false` in your configuration.
