plugins {
    id "io.micronaut.build.internal.security-base"
    id 'java-library'
}
repositories {
    mavenCentral()
}
dependencies {
    testImplementation(platform("io.micronaut.platform:micronaut-platform:${libs.versions.micronaut.platform.get()}"))
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

//TODO remove once Micronaut Test ships Spock version compatible with Groovy 5
configurations.all {
    resolutionStrategy {
        force("org.spockframework:spock-core:2.4-groovy-5.0")
    }
}
