[versions]
managed-nimbus-jose-jwt = "10.8"
managed-jjwt = "0.13.0"
micronaut = "5.0.0-M17"
micronaut-platform = "4.10.10"
awaitility = "4.3.0"
geb = "8.0.1"
selenium = "4.41.0"
system-stubs-core = "2.1.8"
unboundid-ldapsdk = "7.0.4"
bouncycastle = "1.70"
bcpkix = "1.70"
micronaut-hibernate-validator = "5.0.0-M1"
micronaut-multitenancy = "6.0.0-M1"
micronaut-cache = "6.0.0-M2"
micronaut-reactor = "4.0.0-M1"
micronaut-serde = "3.0.0-M2"
micronaut-servlet = "6.0.0-M2"
micronaut-session = "5.0.0-M1"
micronaut-views = "6.0.0-M1"
micronaut-validation = "5.0.0-M1"
micronaut-test = "5.0.0-M6"
micronaut-data = "5.0.0-M5"
micronaut-sql = "7.0.0-M8"
graalvm-native-buildtools = "0.11.5"
jsonassert = "1.5.3"
commons-codec = "1.20.0"

[libraries]
# Core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }
micronaut-cache = { module = "io.micronaut.cache:micronaut-cache-bom", version.ref = "micronaut-cache" }
micronaut-hibernate-validator = { module = "io.micronaut.beanvalidation:micronaut-hibernate-validator-bom", version.ref = "micronaut-hibernate-validator" }
micronaut-multitenancy = { module = "io.micronaut.multitenancy:micronaut-multitenancy-bom", version.ref = "micronaut-multitenancy" }
micronaut-reactor = { module = "io.micronaut.reactor:micronaut-reactor-bom", version.ref = "micronaut-reactor" }
micronaut-serde = { module = "io.micronaut.serde:micronaut-serde-bom", version.ref = "micronaut-serde" }
micronaut-servlet = { module = "io.micronaut.servlet:micronaut-servlet-bom", version.ref = "micronaut-servlet" }
micronaut-session = { module = "io.micronaut.session:micronaut-session-bom", version.ref = "micronaut-session" }
micronaut-views = { module = "io.micronaut.views:micronaut-views-bom", version.ref = "micronaut-views" }
micronaut-validation = { module = "io.micronaut.validation:micronaut-validation-bom", version.ref = "micronaut-validation" }
micronaut-data = { module = "io.micronaut.data:micronaut-data-bom", version.ref = "micronaut-data" }
micronaut-sql = { module = "io.micronaut.sql:micronaut-sql-bom", version.ref = "micronaut-sql" }

managed-nimbus-jose-jwt = { module = "com.nimbusds:nimbus-jose-jwt", version.ref = "managed-nimbus-jose-jwt" }
managed-jjwt-api = { module = "io.jsonwebtoken:jjwt-api", version.ref = "managed-jjwt" }
managed-jjwt-impl = { module = "io.jsonwebtoken:jjwt-impl", version.ref = "managed-jjwt" }
managed-jjwt-jackson = { module = "io.jsonwebtoken:jjwt-jackson", version.ref = "managed-jjwt" }

geb-spock = { module = "org.apache.groovy.geb:geb-spock", version.ref = "geb" }
selenium-api = { module = "org.seleniumhq.selenium:selenium-api", version.ref = "selenium" }
selenium-chrome-driver = { module = "org.seleniumhq.selenium:selenium-chrome-driver", version.ref = "selenium" }
selenium-firefox-driver = { module = "org.seleniumhq.selenium:selenium-firefox-driver", version.ref = "selenium" }
selenium-remote-driver = { module = "org.seleniumhq.selenium:selenium-remote-driver", version.ref = "selenium" }
selenium-support = { module = "org.seleniumhq.selenium:selenium-support", version.ref = "selenium" }
unboundid-ldapsdk = { module = "com.unboundid:unboundid-ldapsdk", version.ref = "unboundid-ldapsdk" }
bcpkix-jdk15on = { module = "org.bouncycastle:bcpkix-jdk15on", version.ref = "bouncycastle" }
bcprov-jdk15on = { module = "org.bouncycastle:bcprov-jdk15on", version.ref = "bouncycastle" }
bcpkix = { module = "org.bouncycastle:bcpkix-jdk15on", version.ref = "bcpkix" }
system-stubs-core = { module = "uk.org.webcompere:system-stubs-core", version.ref = "system-stubs-core" }
jsonassert = { module = 'org.skyscreamer:jsonassert', version.ref = 'jsonassert'}
commons-codec = {module = 'commons-codec:commons-codec', version.ref = 'commons-codec'}
testcontainers-selenium = { module = "org.testcontainers:testcontainers-selenium"}
testcontainers-junit-jupiter = { module = "org.testcontainers:testcontainers-junit-jupiter"}
testcontainers-mysql = { module = "org.testcontainers:testcontainers-mysql" }
testcontainers = { module = "org.testcontainers:testcontainers" }
awaitility = { module = 'org.awaitility:awaitility', version.ref = 'awaitility' }
graalvm-native-buildtools = { module = "org.graalvm.buildtools.native:org.graalvm.buildtools.native.gradle.plugin", version.ref = "graalvm-native-buildtools" }

