plugins {
    id 'java-library'
    id 'org.graalvm.buildtools.native'
    id "io.micronaut.build.internal.security-tests"
}

dependencies {
    testAnnotationProcessor(mn.micronaut.inject.java)
    testImplementation(mn.micronaut.http)
    testImplementation(mn.micronaut.json.core)
    testImplementation(mn.micronaut.http.client)
    testImplementation(mn.micronaut.http.server.netty)
    testImplementation(projects.micronautSecurity)
    testImplementation(projects.micronautSecurityJwt)
    testImplementation(mnTest.micronaut.test.junit5)

    testAnnotationProcessor(mnSerde.micronaut.serde.processor)
    testImplementation(mnSerde.micronaut.serde.jackson)
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}
graalvmNative {
    metadataRepository {
        enabled = true
    }
    binaries {
        test {
            // Ensure certain JUnit Platform classes are initialized at run time for native tests
            buildArgs.addAll([
                '--initialize-at-build-time=org.junit.platform.launcher.core.HierarchicalOutputDirectoryCreator,org.junit.platform.launcher.core.LauncherPhase,org.junit.platform.launcher.core.DiscoveryIssueNotifier,org.junit.platform.engine.support.store.NamespacedHierarchicalStore$EvaluatedValue'
            ])
            javaLauncher.set(javaToolchains.launcherFor {
                languageVersion = JavaLanguageVersion.of(21)
            })
        }
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}
