// Aggregates the coverage that every test in the repository, test suites included, gives to the published modules,
// and verifies the coverage of each of them.
// ./gradlew :test-suite-coverage:check -DpredictiveTestSelection=false
plugins {
    base
    `jacoco-report-aggregation`
}

repositories {
    mavenCentral()
}

val testProjects = rootProject.subprojects.filter { it != project && !it.name.endsWith("-bom") }
// The modules applying the security-module convention plugin, without the TCKs.
val coveredProjects = testProjects.filter { it.name.startsWith("micronaut-security") && !it.name.endsWith("-tck") }

val coveredModules = configurations.dependencyScope("coveredModules")
val coveredClasses = configurations.resolvable("coveredClasses") {
    extendsFrom(coveredModules.get())
    isTransitive = false
    attributes {
        attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage.JAVA_RUNTIME))
        attribute(Category.CATEGORY_ATTRIBUTE, objects.named(Category.LIBRARY))
        attribute(LibraryElements.LIBRARY_ELEMENTS_ATTRIBUTE, objects.named(LibraryElements.CLASSES))
    }
}

dependencies {
    // execution data of the tests of every project
    testProjects.forEach { add("jacocoAggregation", project(it.path)) }
    coveredProjects.forEach { add(coveredModules.name, project(it.path)) }
}

reporting {
    reports {
        register<JacocoCoverageReport>("testCodeCoverageReport") {
            testSuiteName = "test"
        }
    }
}

fun classesOf(modules: List<Project>) = coveredClasses.map { classes ->
    classes.filter { file -> modules.any { file.startsWith(it.projectDir) } }.asFileTree.matching {
        // generated by the Micronaut build plugins
        exclude("io/micronaut/security/info/**")
    }
}

val testCodeCoverageReport = tasks.named<JacocoReport>("testCodeCoverageReport") {
    classDirectories.setFrom(classesOf(coveredProjects))
}

// Predictive test selection, which the Micronaut build plugins enable for local builds, runs a subset of the tests.
val everyTestRuns = providers.environmentVariable("PREDICTIVE_TEST_SELECTION")
    .orElse(providers.systemProperty("predictiveTestSelection"))
    .map { !it.toBoolean() }
    .orElse(providers.environmentVariable("GITHUB_ACTIONS").map { true }.orElse(false))

val coverageVerifications = coveredProjects.map { module ->
    // Minimum ratio of lines and branches that the tests have to cover, set in the gradle.properties of the module.
    val minimums = listOf("LINE" to "lineCoverageMinimum", "BRANCH" to "branchCoverageMinimum").map { (counter, property) ->
        counter to requireNotNull(module.findProperty(property)) {
            "Set $property in ${module.projectDir.name}/gradle.properties"
        }.toString().toBigDecimal()
    }
    val taskName = module.name.split("-").joinToString("") { it.replaceFirstChar(Char::uppercase) }
        .replaceFirstChar(Char::lowercase) + "CoverageVerification"
    tasks.register<JacocoCoverageVerification>(taskName) {
        description = "Verifies the coverage that every test in the repository gives to ${module.name}"
        group = LifecycleBasePlugin.VERIFICATION_GROUP
        executionData.setFrom(testCodeCoverageReport.map { it.executionData })
        classDirectories.setFrom(classesOf(listOf(module)))
        onlyIf("every test runs") { everyTestRuns.get() }
        violationRules {
            rule {
                minimums.forEach { (type, ratio) ->
                    limit {
                        counter = type
                        minimum = ratio
                    }
                }
            }
        }
    }
}

tasks.named("check") {
    dependsOn(coverageVerifications)
    val verified = everyTestRuns
    doFirst {
        if (!verified.get()) {
            logger.warn("Coverage is not verified: predictive test selection runs a subset of the tests. Use -DpredictiveTestSelection=false")
        }
    }
}
