The LDAP authentication in Micronaut supports configuration of one or more LDAP servers to authenticate with. Each server has it's own settings and can be enabled or disabled.

include::{includedir}configurationProperties/io.micronaut.security.ldap.configuration.LdapConfiguration.adoc[]
include::{includedir}configurationProperties/io.micronaut.security.ldap.configuration.LdapConfiguration$ContextConfiguration.adoc[]
include::{includedir}configurationProperties/io.micronaut.security.ldap.configuration.LdapConfiguration$SearchConfiguration.adoc[]
include::{includedir}configurationProperties/io.micronaut.security.ldap.configuration.LdapConfiguration$GroupConfiguration.adoc[]

== Returned User Attributes

When `micronaut.security.ldap.*.search.attributes` is not set, the user search requests every attribute the manager account is allowed to read. The attributes are then exposed to your api:security.ldap.ContextAuthenticationMapper[] and api:security.ldap.group.LdapGroupProcessor[] implementations through the api:security.ldap.context.LdapSearchResult[].

To avoid exposing password hashes to application code, the attributes listed in `micronaut.security.ldap.*.search.excluded-attributes` are stripped from the search results before they reach your code. By default `userPassword` and `unicodePwd` are excluded. Matching is case-insensitive. Set the property to an empty list to disable the exclusion, or extend the list to strip additional sensitive attributes.

It is recommended to set `micronaut.security.ldap.*.search.attributes` explicitly to the minimal set of attributes your application needs, for example:

[configuration]
----
micronaut:
  security:
    ldap:
      default:
        search:
          attributes:
            - uid
            - cn
            - mail
----

NOTE: The group search only requests the attribute configured with `micronaut.security.ldap.*.groups.attribute` (`cn` by default). If you set `micronaut.security.ldap.*.groups.filter-attribute`, make sure that attribute is included in `micronaut.security.ldap.*.search.attributes`, since the value is read from the user search result.

TIP: To connect to an LDAP server with SSL, set the standard Java system properties to the values appropriate for your server.
```
-Djavax.net.ssl.trustStore="<path to truststore file>"
-Djavax.net.ssl.trustStorePassword="<passphrase for truststore>"
```
