The resource owner password credentials grant is described in https://tools.ietf.org/html/rfc6749#section-4.3[RFC 6749]. In short, credentials are passed directly to the token endpoint and if authentication succeeds, the token endpoint response with the appropriate token.

The process that handles the token response onward is the same for both authorization code and password grants. See the following high level flow diagrams:

OAuth 2.0 Provider

image::oauth-password.svg[]

OpenID Provider

image::openid-password.svg[]

In Micronaut, the password grant is supported by setting the `grant-type` configuration option in the client configuration. For example:

[source, yaml]
----
micronaut:
  security:
    oauth2:
      clients:
        github:
          grant-type: password
----

NOTE: This example above is not intended to be a complete configuration reference

When a client is configured for the password grant type, the authorization code endpoints will not be available and instead an api:security.authentication.AuthenticationProvider[] will be created that will participate in the <<login,normal login flow>>.




