Moreover, you can configure endpoint authentication and authorization access with an Intercept URL Map:

[configuration]
----
include::{testssecurity}/security/securityRule/intercepturlmap/InterceptUrlMapSpec.groovy[tag=yamlconfig,indent=0]
----

- pattern `/images/*` enables access to authenticated and not authenticated users
- pattern `/books` enables access for everyone authenticated
- pattern `/books/grails` enables access for users who are granted any of the specified roles.

As you see in the previous code listing, any endpoint is identified by a combination of pattern
and an optional HTTP method.

If a given request URI matches more than one intercept url map, the one that specifies an http method that matches the request method will be used. If there are multiple mappings that do not specify a method and match the request URI, then the first mapping will be used. For example:

The example below defines that all HTTP requests to URIs matching the pattern `/v1/myResource/**` and using HTTP method `GET` will be accessible to everyone. Requests matching the same URI pattern but using a different HTTP method than `GET` require fully authenticated access.

[configuration]
----
micronaut:
  security:
    intercept-url-map:
      - pattern: /v1/myResource/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /v1/myResource/**
        access:
          - isAuthenticated()
----

- accessing `/v1/myResource/**` with a GET request does not require authentication
- accessing `/v1/myResource/**` with a request that isn't GET requires authentication

IMPORTANT: When a ann:security.annotation.Secured[] annotation is provided with a set of roles, then a user will have to access to that resource if they have *at least one* of thoose roles, not all.
