As illustrated below, you can use the ann:security.annotation.Secured[] annotation to control
access to controllers or controller methods.

[source, groovy]
----
include::{testssecurity}/security/securityRule/secured/ExampleController.java[tag=exampleControllerPlusImports,indent=0]
----

<1> Authenticated users are able to access `authenticated` Controller's action.
<2> Users granted role `ROLE_ADMIN` or `ROLE_X` roles can access `withroles` Controller's action.
<3> Anonymous users (authenticated and not authenticated users) can access `anonymous` Controller's action.

Alternatively, you can use https://jcp.org/en/jsr/detail?id=250[JSR_250] annotations (`javax.annotation.security.PermitAll`, `javax.annotation.security.RolesAllowed`, `javax.annotation.security.DenyAll`):

[source, java]
----
include::{testssecurity}/security/securityRule/permitall/ExampleController.java[tag=exampleControllerPlusImports,indent=0]
----

<1> Users granted role `ROLE_ADMIN` or `ROLE_X` roles can access `withroles` Controller's action.
<2> Anonymous users (authenticated and not authenticated users) can access `anonymous` Controller's action.

NOTE: The use of JSR 250 annotations requires `io.micronaut:micronaut-security-annotations` to be in the annotation processor classpath (`annotationProcessor`, `kapt`, `compileOnly`) respectively for Java, Kotlin, Groovy.

