plugins {
    id 'java-library'
    id 'groovy'
    id("io.micronaut.build.internal.common")
    id "io.micronaut.build.internal.security-base"
}

dependencies {
    compileOnly(mn.micronaut.inject.groovy)
    implementation(mnTest.micronaut.test.spock)
    implementation(mn.micronaut.http.server.netty)
    implementation(mn.micronaut.http.client)
}

spotless {
    java {
        targetExclude("**/testutils/**")
    }
    groovy {
        targetExclude("**/testutils/**")
    }
}

tasks.withType(Checkstyle) {
    enabled = false
}
//TODO remove once Micronaut Test ships Spock version compatible with Groovy 5
configurations.all {
    resolutionStrategy {
        force("org.spockframework:spock-core:2.4-groovy-5.0")
    }
}
