micronaut:
  security:
    ldap:
      default:
        context:
          managerDn: "cn=admin,dc=example,dc=com"
          managerPassword: "password"
        search:
          base: "dc=example,dc=com"
        groups:
          enabled: true
          base: "dc=example,dc=com"
