ARG KEYCLOAK_VERSION=16.1.1

# Grab the x86 version of keycloak for the tools
FROM jboss/keycloak:$KEYCLOAK_VERSION as keycloak

FROM ubuntu:latest

ARG KEYCLOAK_VERSION

# Taken from https://github.com/keycloak/keycloak-containers/blob/main/server/Dockerfile (check history for version changes)
ENV KEYCLOAK_VERSION $KEYCLOAK_VERSION
ENV JDBC_POSTGRES_VERSION 42.2.5
ENV JDBC_MYSQL_VERSION 8.0.22
ENV JDBC_MARIADB_VERSION 2.5.4
ENV JDBC_MSSQL_VERSION 8.2.2.jre11

ENV LAUNCH_JBOSS_IN_BACKGROUND 1
ENV PROXY_ADDRESS_FORWARDING false
ENV JBOSS_HOME /opt/jboss/keycloak
ENV LANG en_US.UTF-8

ARG GIT_REPO
ARG GIT_BRANCH

ARG KEYCLOAK_DIST=https://github.com/keycloak/keycloak/releases/download/$KEYCLOAK_VERSION/keycloak-$KEYCLOAK_VERSION.tar.gz

USER root

RUN apt update
RUN apt --assume-yes install curl gzip hostname openssl tar
RUN apt --assume-yes install openjdk-11-jdk-headless

COPY --from=keycloak /opt/jboss/tools /opt/jboss/tools

RUN /opt/jboss/tools/build-keycloak.sh

USER 1000

EXPOSE 8080
EXPOSE 8443

ENTRYPOINT [ "/opt/jboss/tools/docker-entrypoint.sh" ]

CMD ["-b", "0.0.0.0"]