plugins {
    id 'io.micronaut.minimal.application' version "$micronautGradlePluginVersion"
    id "com.gradleup.shadow" version "9.4.2"
}

repositories {
    mavenCentral()
}

application {
    mainClass = 'io.micronaut.security.test.aot.authserver.Application'
}

micronaut {
    version = libs.versions.micronaut.platform.get()
    runtime("netty")
    testRuntime("junit5")
    processing {
        incremental(true)
        annotations("io.micronaut.security.test.aot.authserver")
    }
}

dependencies {
    implementation(mn.micronaut.http.client)
    implementation(mn.micronaut.management)
    implementation(mnSerde.micronaut.serde.jackson)
    testImplementation(platform("io.micronaut.platform:micronaut-platform:${libs.versions.micronaut.platform.get()}"))
    testImplementation("org.junit.platform:junit-platform-launcher")
}

shadowJar {
    archiveBaseName.set('authserver')
    archiveClassifier.set('')
    archiveVersion.set('')
}

configurations.all {
    resolutionStrategy {
        preferProjectModules()
    }
}
