A https://tools.ietf.org/html/rfc7517[JSON Web Key (JWK)] is a JSON object that represents a cryptographic key. You can use a remote JWK Set, A JSON object that represents a set of JWKs, to validate JWT signatures.

You can configure a remote JWKS as a signature validator:

[configuration]
----
include::{testssecurityjwt}/jwks/JwksSpec.groovy[indent=0, tag=yamljwksconfig]
----

The previous snippet creates a link:{api}/io/micronaut/security/token/jwt/nimbus/ReactiveJwksSignature.html[ReactiveJwksSignature] bean with a `awscognito` name qualifier.

If you have the https://docs.micronaut.io/latest/guide/#httpClient[Micronaut HTTP Client] on the classpath, then it will be used to retrieve the remote JWK Set. This allows for the configuration settings of the HTTP Client to be applied when fetching the resource. If a named service-specific client exists and the name of the service matches the name of the configured JWKS provider name, then that specific client instance will be used, otherwise a default Http Client instance (with any global configuration settings from `micronaut.http.client.*` applied) will be used. If the Micronaut HTTP Client is not on the classpath, then the implementation will fall back to the internal resource fetching mechanism of the external JWT library dependency.

For example, to use an HTTP proxy for the fetching of the JWK Set from the above example:

[configuration]
----
include::{testssecurityjwt}/jwks/JwksSpec.groovy[indent=0, tag=yamlserviceclientconfig]
----

Note that the same approach will be applied when using a `jwks_uri` supplied via <<openid-authorization-code, Open ID Connect>> metadata.

When a JWT is verified, a key of the JWK Set is only used if its Key ID (`kid`) matches the token header (when the token carries one), its `use` is absent or `sig`, its `key_ops` is absent or contains `verify`, and its `alg` is absent or equal to the token `alg` header. Keys published for encryption, or bound to a different algorithm, are never used to verify a signature.

By default, keys of any key type (`kty`) are used. If you set `micronaut.security.token.jwt.signatures.jwks.*.key-type` (for example `RSA` or `EC`), only keys of that key type are used to verify tokens. The JWKS configurations created automatically for the `jwks_uri` of <<openid-authorization-code, Open ID Connect>> clients do not restrict the key type.

The https://docs.micronaut.io/latest/guide/#httpClient[Micronaut HTTP Client] based implementation can be explicitly disabled in favor of the JWT library's internal resource fetching implementation by explicitly setting `micronaut.security.token.jwt.signatures.jwks-client.http-client.enabled=false`. For example:

[configuration]
----
include::{testssecurityjwt}/jwks/JwksSpec.groovy[indent=0, tag=yamlservicefallbackclientconfig]
----

### Exposing your Application's Json Web Key Set (JKWS)

If you want to expose your own JWK Set, read the <<keys, Keys Controller>> section.

