The minimum requirements to allow authorization with an OAuth 2.0 provider are:

* Configuration of the authorization endpoint
* Configuration of the token endpoint
* Configuration of the client id and secret
* An implementation of api:security.oauth2.endpoint.token.response.OauthAuthenticationMapper[]

Configuration is quite simple. For example to configure authorization with Github:

[source,yaml]
----
micronaut:
  security:
    oauth2:
      clients:
        github: // <1>
          client-id: <<my client id>> // <2>
          client-secret: <<my client secret>> // <3>
          scopes: // <4>
            - user:email
            - read:user
          authorization:
            url: https://github.com/login/oauth/authorize // <5>
          token:
            url: https://github.com/login/oauth/access_token // <6>
            auth-method: client-secret-post // <7>
----

<1> Configure a client. The name here is arbitrary
<2> The client id
<3> The client secret
<4> The desired scopes (OPTIONAL)
<5> The authorization endpoint URL
<6> The token endpoint URL
<7> The token endpoint authentication method. One of api:security.oauth2.endpoint.AuthenticationMethod[]. Choose the one your provider requires.

Authentication methods are not clearly defined in link:https://tools.ietf.org/html/rfc6749#section-3.2.1[RFC 6749], however most OAuth 2.0 providers either accept `client-secret-basic` (basic authentication with id and secret), or `client-secret-post` (client id and secret are sent in the request body).

TIP: To disable a specific client for any given environment, set `enabled: false` within the client configuration.
